# Generated by Django 5.0.2 on 2024-04-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [ # Зависимостей нет, так как это первая миграция
    ]

    operations = [
        migrations.CreateModel( # Создание модели Category
            name='Category', # Название модели
            fields=[ # Определение полей модели
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)), # Поле name (название категории)
            ],
        ),
        migrations.CreateModel(  # Создание модели Product
            name='Product', # Название модели
            fields=[ # Определение полей модели
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Поле ID
                ('name', models.CharField(max_length=50)), # Поле name (название продукта)
                ('description', models.TextField(blank=True, default='')), # Поле description (описание продукта)
                ('price', models.DecimalField(decimal_places=2, default=999999.99, max_digits=8)), # Поле price (цена продукта)
                ('quantity', models.PositiveSmallIntegerField(default=0)), # Поле quantity (количество продукта)
                ('date_added', models.DateTimeField(auto_now_add=True)),  # Поле date_added (дата добавления продукта)
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)), # Поле rating (рейтинг продукта)
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework5.category')), # Связь с моделью Category
            ],
        ),
    ]