# Generated by Django 5.0.2 on 2024-04-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ # Указание зависимости от предыдущей миграции
        ('homework5', '0001_initial'),  # Зависимость от первой миграции
    ]
# Операции, которые будут выполнены в рамках данной миграции
    operations = [
        migrations.AlterField( # Изменение поля description в модели Product
            model_name='product', # Название модели, в которой будет изменено поле
            name='description', # Название изменяемого поля
            field=models.TextField(blank=True, default='Это прекрасный продукт!'), # Новое определение поля description
        ),
        migrations.AlterField( # Изменение поля price в модели Product
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8), # Новое определение поля price
        ),
    ]